### ISSUE TITLE
listBuilds with filter throws INVALID_ARGUMENT: Request contains an invalid argument

### ISSUE THREAD

**Issue by OleksiiKachan** [googleapis/nodejs-cloudbuild#299] opened 2022-01-19 22:23 UTC
I have a cloudfunction triggered by cloudbuilds. the purpouse of function is to cancel running builds from same branch and trigger.
filter argument does not work and has no proper documentation

#### Environment details

  - OS: gc cloudfunctions
  - Node.js version: 14
  - yarn version: 1.22.17
  - `@google-cloud/cloudbuild` version: 2.6.0

#### Steps to reproduce

```js
const { CloudBuildClient } = require('@google-cloud/cloudbuild');

const parseBuild = (data) => JSON.parse(Buffer.from(data, "base64").toString());

module.exports["gcb-canceler"] = async (buildStream) => {
  const parsedBuild = parseBuild(buildStream.data);
  const buildStatus = parsedBuild.status;

  const buildTriggerId = parsedBuild.buildTriggerId;
  const buildId = parsedBuild.id;
  const projectId = parsedBuild.projectId
  const targetBranch = parsedBuild.substitutions.BRANCH_NAME

  if (buildStatus === `QUEUED` && buildId && targetBranch && buildTriggerId) {
    const cb = new CloudBuildClient();

    const filter = `id!="${buildId}" AND substitutions.BRANCH_NAME="${targetBranch}" AND buildTriggerId="${buildTriggerId}" AND status<=2`;
    
    console.log(filter);

    const request = {
      projectId,
      filter
    };

    const [builds] = await cb.listBuilds(request)
  }
}
```

throws INVALID_ARGUMENT. filter expression is correct as I test it by running `gcloud builds list --filter="EXPRESSION"` and it returns me list of builds.

Thanks!

**Comment by ace-n** [comment] 2022-03-24 19:06
Hi @OleksiiKachan,

I think the issue is `id` - the Cloud Build client libraries don't recognize this; they use `build_id` (or `trigger_id`) instead as you can see [here](https://cloud.google.com/build/docs/view-build-results#filtering_build_results_using_queries).

Can you try replacing `id` with either `build_id` or `trigger_id`, and let us know if that works?

Thanks! 🙂

**Comment by pattishin** [comment] 2022-04-07 18:17
@OleksiiKachan 👋🏼  Has replacing `id` resolved the issue for you? Do let us know if this is still a problem for you!

**Comment by pattishin** [comment] 2022-04-21 18:53
Syncing back to this issue! I have re-created the above issue below (very simple filter to exclude build) and confirmed that the suggestion given by @ace-n to switch from `id` to `build_id` in the code works. This also goes with the terminal command.

See below:
```
// Using version: @google-cloud/cloudbuild 2.6.0
const { CloudBuildClient } = require("@google-cloud/cloudbuild");

// Note: Cloud build from build history
// https://console.cloud.google.com/cloud-build
const main = async() =>{
    const cb = new CloudBuildClient();
    const request = {
        filter: ":build_id!=YOUR_CLOUD_BUILD_ID",
        projectId: "YOUR_PROJECT_ID"
    };
    const [builds] = await cb.listBuilds(request);
    console.log(builds);
}
main();
```
Corresponding command: `gcloud builds list --filter="build_id!=YOUR_CLOUD_BUILD_ID"`

Since this has been confirmed, and no other activity has happened within this issue, going ahead and closing this. Please reopen the issue if you run into this problem again!

**Closed by pattishin** 2022-04-21 18:53 UTC
Labels: type: bug, api: cloudbuild, priority: p2
